title: SuperC documentation
google_analytics:
theme: jekyll-theme-minimal
incremental: false
plugins:
  - jekyll-tabs

keep_files:
  - assets/jslinux/os/files

docs_nav:
  - index.md
  - docs/defer.md
  - docs/defer_auto.md
  - docs/symbols.md
  - docs/break_n.md
  - docs/switch_ranges.md
  - docs/nullish_coalescing.md
  - docs/methods.md
  - docs/operator_overload.md
  - docs/function_overload.md
  - docs/function_default_arguments.md
  - docs/namespaces.md
  - docs/c_backwards_compat.md
  - docs/struct_embedding.md
  - docs/soft_objects.md
  - docs/lambdas.md
  - docs/defer_edge_cases.md
